# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('usage', models.CharField(blank=True, max_length=64, null=True, verbose_name='用途')),
                ('system', models.CharField(choices=[('ubuntu', 'ubuntu'), ('centos7', 'centos7')], default='cenots7', max_length=64, verbose_name='操作系统类型')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='cpu个数')),
                ('mem', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('disk_total', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器资产表',
                'verbose_name_plural': '服务器资产表',
                'db_table': 'wisops_server_info_t',
            },
        ),
    ]
